version: "3.8"

services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222" # Client connections
      - "8222:8222" # HTTP monitoring
    command: -js # Enable JetStream
    volumes:
      - nats-data:/data/nats-server
    healthcheck:
      test: ["CMD", "nats-server", "--help"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  nats-data:
    driver: local
